In [4]:
#READ THE CSV FILE

import pandas as pd #the library we will be using 
df = pd.read_csv("/Users/prijinagurung/Desktop/PythonA/Data-analysis-python-/pandas_dataset.csv") #importing the dataset
df

ModuleNotFoundError: No module named 'pandas'

In [ ]:
df.head() #printing the first 5 rows

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
2,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
3,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
4,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0

In [ ]:
#RENAME COLUMNS

#the updated dataset already has column names in lowercase and separated by _

In [ ]:
#DROP UNNECESSARY ROWS

df_dropped = df.drop(df.index[0], axis = 0) #removing the 1st row after header since it is blank
#axis = 0 shows that the operation is on a row 
df_dropped.head()

df_dropped = df_dropped.reset_index(drop = True) #resetting the index to 0,1,2,... from 1,2,3,...
#here, drop = True indicates that the old index will be deleted
df_dropped.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

In [ ]:
#DROP COLUMNS

df_dropped = df_dropped.drop("order_date", axis = 1) 
#axis = 1 shows that the operation is on a column
df_dropped.head()

#I decided to drop the order_date column since there are no questions that require it for this particular assignment.

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.0,5500.0

In [ ]:
#COUNT MISSING VALUES
print(df_dropped.isnull().sum()) #this displays the null values in each of the columns

order_id         0
customer_name    1
category         0
product          0
city             1
quantity         1
unit_price       1
status           1
sales            3
profit           3
discount         3
dtype: int64