In [344]:
#READ THE CSV FILE

import pandas as pd #the library we will be using 
df = pd.read_csv("/Users/prijinagurung/Desktop/PythonA/Data-analysis-python-/pandas_dataset.csv") #importing the dataset
df

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
2,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
3,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
4,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
5,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0
6,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,1/22/2026,Completed,8800.0,1760.0,440.0
7,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000.0,10000.0,5000.0
8,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,2/2/2026,Pending,22500.0,4500.0,1125.0
9,1009.0,Puja,Electronics,Tablet,Kathmandu,1.0,NaN,2/5/2026,Completed,NaN,NaN,NaN
10,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,2/9/2026,Completed,7000.0,1400.0,350.0
11,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,2/12/2026,Completed,9000.0,1800.0,450.0
12,1012.0,Suman,Furniture,Bookshelf,Pokhara,1.0,15000.0,2/15/2026,NaN,15000.0,3000.0,750.0
13,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,2/18/2026,Completed,56000.0,11200.0,5600.0
14,1014.0,Kabita,Books,SQL Book,Kathmandu,3.0,2800.0,2/20/2026,Completed,8400.0,1680.0,420.0
15,1015.0,NaN,Clothing,Jeans,Bhaktapur,2.0,4200.0,2/23/2026,Cancelled,8400.0,1680.0,420.0
16,1016.0,Alisha,Electronics,Keyboard,Pokhara,4.0,3500.0,3/1/2026,Completed,14000.0,2800.0,700.0
17,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,3/5/2026,Completed,22000.0,4400.0,1100.0
18,1018.0,Sneha,Clothing,Sweater,Lalitpur,2.0,5000.0,3/8/2026,Pending,10000.0,2000.0,500.0
19,1019.0,Ashim,Books,Excel Book,Bhaktapur,NaN,2500.0,3/11/2026,Completed,NaN,NaN,NaN
20,1020.0,Rita,Electronics,Smart Watch,Kathmandu,2.0,12000.0,3/15/2026,Completed,24000.0,4800.0,1200.0
21,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
22,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,1/25/2026,Completed,50000.0,10000.0,5000.0
23,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,2/18/2026,Completed,56000.0,11200.0,5600.0
24,1024.0,Nisha,Electronics,Mouse,Kathmandu,2.0,85000.0,1/5/2026,Completed,NaN,600.0,150.0
25,1025.0,Bikash,Furniture,Lamp,Lalitpur,1.0,18000.0,1/8/2026,Completed,9000.0,NaN,450.0
26,1026.0,Sarita,Electronics,Shirt,Bhaktapur,3.0,4500.0,1/12/2026,Pending,5000.0,1000.0,NaN

In [345]:
df.head() #printing the first 5 rows

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
2,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
3,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
4,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0

In [346]:
#RENAME COLUMNS

#the updated dataset already has column names in lowercase and separated by _

In [347]:
#DROP UNNECESSARY ROWS

df_dropped = df.drop(df.index[0], axis = 0) #removing the 1st row after header since it is blank
#axis = 0 shows that the operation is on a row 
df_dropped.head()

df_dropped = df_dropped.reset_index(drop = True) #resetting the index to 0,1,2,... from 1,2,3,...
#here, drop = True indicates that the old index will be deleted
df_dropped.head()

,order_id,customer_name,category,product,city,quantity,unit_price,order_date,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,1/5/2026,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,1/8/2026,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,1/12/2026,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,1/15/2026,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,1/20/2026,Cancelled,55000.0,11000.0,5500.0

In [348]:
#DROP COLUMNS

df_dropped = df_dropped.drop("order_date", axis = 1) 
#axis = 1 shows that the operation is on a column
df_dropped.head()

#I decided to drop the order_date column since there are no questions that require it for this particular assignment.

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.0,5500.0

In [349]:
#COUNT MISSING VALUES
print(df_dropped.isnull().sum()) #this displays the null values in each of the columns

order_id         0
customer_name    1
category         0
product          0
city             1
quantity         1
unit_price       1
status           1
sales            3
profit           3
discount         3
dtype: int64

In [350]:
#HANDLE MISSING VALUES
#a) Drop rows based on column

df_dropped = df_dropped.dropna(subset = ['sales'], axis = 0)
#dropping rows (axis=0) using dropna having null values in sales column
df_dropped

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.0,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,Completed,18000.0,3600.0,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,Pending,13500.0,2700.0,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,Completed,13000.0,2600.0,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.0,5500.0
5,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,Completed,8800.0,1760.0,440.0
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.0,5000.0
7,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,Pending,22500.0,4500.0,1125.0
9,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,Completed,7000.0,1400.0,350.0
10,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,Completed,9000.0,1800.0,450.0
11,1012.0,Suman,Furniture,Bookshelf,Pokhara,1.0,15000.0,NaN,15000.0,3000.0,750.0
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.0,5600.0
13,1014.0,Kabita,Books,SQL Book,Kathmandu,3.0,2800.0,Completed,8400.0,1680.0,420.0
14,1015.0,NaN,Clothing,Jeans,Bhaktapur,2.0,4200.0,Cancelled,8400.0,1680.0,420.0
15,1016.0,Alisha,Electronics,Keyboard,Pokhara,4.0,3500.0,Completed,14000.0,2800.0,700.0
16,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,Completed,22000.0,4400.0,1100.0
17,1018.0,Sneha,Clothing,Sweater,Lalitpur,2.0,5000.0,Pending,10000.0,2000.0,500.0
19,1020.0,Rita,Electronics,Smart Watch,Kathmandu,2.0,12000.0,Completed,24000.0,4800.0,1200.0
20,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.0,17000.0
21,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.0,5000.0
22,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.0,5600.0
24,1025.0,Bikash,Furniture,Lamp,Lalitpur,1.0,18000.0,Completed,9000.0,NaN,450.0
25,1026.0,Sarita,Electronics,Shirt,Bhaktapur,3.0,4500.0,Pending,5000.0,1000.0,NaN

In [351]:
#HANDLE MISSING VALUES
#b) Fill missing values

df_dropped['profit'] = df_dropped['profit'].fillna(df_dropped['profit'].mean())
#fillna fills null values in profit column with the mean of existing values in profit

df_dropped['discount'] = df_dropped['discount'].fillna(df_dropped['discount'].median())
#filling null values in discount columnn with median

df_dropped

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.000000,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,Completed,18000.0,3600.000000,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,Pending,13500.0,2700.000000,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,Completed,13000.0,2600.000000,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.000000,5500.0
5,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,Completed,8800.0,1760.000000,440.0
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.000000,5000.0
7,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,Pending,22500.0,4500.000000,1125.0
9,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,Completed,7000.0,1400.000000,350.0
10,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,Completed,9000.0,1800.000000,450.0
11,1012.0,Suman,Furniture,Bookshelf,Pokhara,1.0,15000.0,NaN,15000.0,3000.000000,750.0
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.000000,5600.0
13,1014.0,Kabita,Books,SQL Book,Kathmandu,3.0,2800.0,Completed,8400.0,1680.000000,420.0
14,1015.0,NaN,Clothing,Jeans,Bhaktapur,2.0,4200.0,Cancelled,8400.0,1680.000000,420.0
15,1016.0,Alisha,Electronics,Keyboard,Pokhara,4.0,3500.0,Completed,14000.0,2800.000000,700.0
16,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,Completed,22000.0,4400.000000,1100.0
17,1018.0,Sneha,Clothing,Sweater,Lalitpur,2.0,5000.0,Pending,10000.0,2000.000000,500.0
19,1020.0,Rita,Electronics,Smart Watch,Kathmandu,2.0,12000.0,Completed,24000.0,4800.000000,1200.0
20,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.000000,17000.0
21,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.000000,5000.0
22,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.000000,5600.0
24,1025.0,Bikash,Furniture,Lamp,Lalitpur,1.0,18000.0,Completed,9000.0,7323.636364,450.0
25,1026.0,Sarita,Electronics,Shirt,Bhaktapur,3.0,4500.0,Pending,5000.0,1000.000000,825.0

In [352]:
#HANDLE MISSING CATEGORICAL DATA

df_dropped['customer_name'] = df_dropped['customer_name'].fillna('Unknown')
#giving a fixed string to replaces the null values with it rather than mean/median
df_dropped

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.000000,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,Completed,18000.0,3600.000000,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,Pending,13500.0,2700.000000,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,Completed,13000.0,2600.000000,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.000000,5500.0
5,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,Completed,8800.0,1760.000000,440.0
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.000000,5000.0
7,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,Pending,22500.0,4500.000000,1125.0
9,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,Completed,7000.0,1400.000000,350.0
10,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,Completed,9000.0,1800.000000,450.0
11,1012.0,Suman,Furniture,Bookshelf,Pokhara,1.0,15000.0,NaN,15000.0,3000.000000,750.0
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.000000,5600.0
13,1014.0,Kabita,Books,SQL Book,Kathmandu,3.0,2800.0,Completed,8400.0,1680.000000,420.0
14,1015.0,Unknown,Clothing,Jeans,Bhaktapur,2.0,4200.0,Cancelled,8400.0,1680.000000,420.0
15,1016.0,Alisha,Electronics,Keyboard,Pokhara,4.0,3500.0,Completed,14000.0,2800.000000,700.0
16,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,Completed,22000.0,4400.000000,1100.0
17,1018.0,Sneha,Clothing,Sweater,Lalitpur,2.0,5000.0,Pending,10000.0,2000.000000,500.0
19,1020.0,Rita,Electronics,Smart Watch,Kathmandu,2.0,12000.0,Completed,24000.0,4800.000000,1200.0
20,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.000000,17000.0
21,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.000000,5000.0
22,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.000000,5600.0
24,1025.0,Bikash,Furniture,Lamp,Lalitpur,1.0,18000.0,Completed,9000.0,7323.636364,450.0
25,1026.0,Sarita,Electronics,Shirt,Bhaktapur,3.0,4500.0,Pending,5000.0,1000.000000,825.0

In [353]:
#DETECT AND REMOVE DUPLICATES

duplicates = df_dropped.duplicated(subset = 'order_id').sum() #counting all the duplicate rows based on order id
print (f"We will remove {duplicates} duplicate rows")

df_dropped[df_dropped.duplicated(subset ='order_id')]
#checking for duplicated rows

We will remove 3 duplicate rows

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount
20,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.0,17000.0
21,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.0,5000.0
22,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.0,5600.0

In [354]:
df_nodup = df_dropped.drop_duplicates(subset = ['order_id'])
df_nodup

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.000000,17000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,Completed,18000.0,3600.000000,900.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,Pending,13500.0,2700.000000,675.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,Completed,13000.0,2600.000000,650.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.000000,5500.0
5,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,Completed,8800.0,1760.000000,440.0
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.000000,5000.0
7,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,Pending,22500.0,4500.000000,1125.0
9,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,Completed,7000.0,1400.000000,350.0
10,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,Completed,9000.0,1800.000000,450.0
11,1012.0,Suman,Furniture,Bookshelf,Pokhara,1.0,15000.0,NaN,15000.0,3000.000000,750.0
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.000000,5600.0
13,1014.0,Kabita,Books,SQL Book,Kathmandu,3.0,2800.0,Completed,8400.0,1680.000000,420.0
14,1015.0,Unknown,Clothing,Jeans,Bhaktapur,2.0,4200.0,Cancelled,8400.0,1680.000000,420.0
15,1016.0,Alisha,Electronics,Keyboard,Pokhara,4.0,3500.0,Completed,14000.0,2800.000000,700.0
16,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,Completed,22000.0,4400.000000,1100.0
17,1018.0,Sneha,Clothing,Sweater,Lalitpur,2.0,5000.0,Pending,10000.0,2000.000000,500.0
19,1020.0,Rita,Electronics,Smart Watch,Kathmandu,2.0,12000.0,Completed,24000.0,4800.000000,1200.0
24,1025.0,Bikash,Furniture,Lamp,Lalitpur,1.0,18000.0,Completed,9000.0,7323.636364,450.0
25,1026.0,Sarita,Electronics,Shirt,Bhaktapur,3.0,4500.0,Pending,5000.0,1000.000000,825.0

In [355]:
#FILTERING AND CREATING NEW COLUMNS

df_nodup[df_nodup['unit_price']>20000] #this displays the output based on the condition applied to dataframe

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.0,17000.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.0,5500.0
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.0,5000.0
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.0,5600.0
16,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,Completed,22000.0,4400.0,1100.0

In [356]:
df_nodup[(df_nodup['unit_price']>10000) & (df_nodup['status']== "Completed")][['customer_name', 'category', 'status']]
#the first big brackets provides the condition that needs to be fulfilled to print
#the second big brackets gives the columns to print

   customer_name     category     status
0          Aarav  Electronics  Completed
1           Sita    Furniture  Completed
6          Nabin    Furniture  Completed
12        Roshan  Electronics  Completed
16         Manoj    Furniture  Completed
19          Rita  Electronics  Completed
24        Bikash    Furniture  Completed

In [357]:
df_nodup['total_amount'] = df_nodup['quantity']*df_nodup['unit_price']-df_nodup['discount']
#creating a new column based on the calculation on existing columns
df_nodup

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount,total_amount
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.000000,17000.0,153000.0
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,Completed,18000.0,3600.000000,900.0,17100.0
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,Pending,13500.0,2700.000000,675.0,12825.0
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,Completed,13000.0,2600.000000,650.0,12350.0
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.000000,5500.0,49500.0
5,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,Completed,8800.0,1760.000000,440.0,8360.0
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.000000,5000.0,45000.0
7,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,Pending,22500.0,4500.000000,1125.0,21375.0
9,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,Completed,7000.0,1400.000000,350.0,6650.0
10,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,Completed,9000.0,1800.000000,450.0,8550.0
11,1012.0,Suman,Furniture,Bookshelf,Pokhara,1.0,15000.0,NaN,15000.0,3000.000000,750.0,14250.0
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.000000,5600.0,50400.0
13,1014.0,Kabita,Books,SQL Book,Kathmandu,3.0,2800.0,Completed,8400.0,1680.000000,420.0,7980.0
14,1015.0,Unknown,Clothing,Jeans,Bhaktapur,2.0,4200.0,Cancelled,8400.0,1680.000000,420.0,7980.0
15,1016.0,Alisha,Electronics,Keyboard,Pokhara,4.0,3500.0,Completed,14000.0,2800.000000,700.0,13300.0
16,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,Completed,22000.0,4400.000000,1100.0,20900.0
17,1018.0,Sneha,Clothing,Sweater,Lalitpur,2.0,5000.0,Pending,10000.0,2000.000000,500.0,9500.0
19,1020.0,Rita,Electronics,Smart Watch,Kathmandu,2.0,12000.0,Completed,24000.0,4800.000000,1200.0,22800.0
24,1025.0,Bikash,Furniture,Lamp,Lalitpur,1.0,18000.0,Completed,9000.0,7323.636364,450.0,17550.0
25,1026.0,Sarita,Electronics,Shirt,Bhaktapur,3.0,4500.0,Pending,5000.0,1000.000000,825.0,12675.0

In [358]:
df_nodup ['customer_type'] = df_nodup['quantity'].apply(lambda x: 'Bulk Buyer' if x>=3 else 'Regular Buyer')
#creating a new columun named customer_type based on the condition applied to quantityt column
#using lambda funciton with the condition makes it applicable to the entire quantity column
df_nodup

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount,total_amount,customer_type
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.000000,17000.0,153000.0,Regular Buyer
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,Completed,18000.0,3600.000000,900.0,17100.0,Regular Buyer
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,Pending,13500.0,2700.000000,675.0,12825.0,Bulk Buyer
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,Completed,13000.0,2600.000000,650.0,12350.0,Regular Buyer
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.000000,5500.0,49500.0,Regular Buyer
5,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,Completed,8800.0,1760.000000,440.0,8360.0,Bulk Buyer
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.000000,5000.0,45000.0,Regular Buyer
7,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,Pending,22500.0,4500.000000,1125.0,21375.0,Bulk Buyer
9,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,Completed,7000.0,1400.000000,350.0,6650.0,Regular Buyer
10,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,Completed,9000.0,1800.000000,450.0,8550.0,Bulk Buyer
11,1012.0,Suman,Furniture,Bookshelf,Pokhara,1.0,15000.0,NaN,15000.0,3000.000000,750.0,14250.0,Regular Buyer
12,1013.0,Roshan,Electronics,Monitor,Lalitpur,2.0,28000.0,Completed,56000.0,11200.000000,5600.0,50400.0,Regular Buyer
13,1014.0,Kabita,Books,SQL Book,Kathmandu,3.0,2800.0,Completed,8400.0,1680.000000,420.0,7980.0,Bulk Buyer
14,1015.0,Unknown,Clothing,Jeans,Bhaktapur,2.0,4200.0,Cancelled,8400.0,1680.000000,420.0,7980.0,Regular Buyer
15,1016.0,Alisha,Electronics,Keyboard,Pokhara,4.0,3500.0,Completed,14000.0,2800.000000,700.0,13300.0,Bulk Buyer
16,1017.0,Manoj,Furniture,Table,Kathmandu,1.0,22000.0,Completed,22000.0,4400.000000,1100.0,20900.0,Regular Buyer
17,1018.0,Sneha,Clothing,Sweater,Lalitpur,2.0,5000.0,Pending,10000.0,2000.000000,500.0,9500.0,Regular Buyer
19,1020.0,Rita,Electronics,Smart Watch,Kathmandu,2.0,12000.0,Completed,24000.0,4800.000000,1200.0,22800.0,Regular Buyer
24,1025.0,Bikash,Furniture,Lamp,Lalitpur,1.0,18000.0,Completed,9000.0,7323.636364,450.0,17550.0,Regular Buyer
25,1026.0,Sarita,Electronics,Shirt,Bhaktapur,3.0,4500.0,Pending,5000.0,1000.000000,825.0,12675.0,Bulk Buyer

In [359]:
#SHAPE OF DATASET BEFORE CLEANING

df.shape

(27, 12)

In [360]:
#SHAPE OF DATASET AFTER CLEANING

print(df_nodup.shape)
df_nodup.head(10)

(20, 13)

,order_id,customer_name,category,product,city,quantity,unit_price,status,sales,profit,discount,total_amount,customer_type
0,1001.0,Aarav,Electronics,Laptop,Kathmandu,2.0,85000.0,Completed,170000.0,34000.0,17000.0,153000.0,Regular Buyer
1,1002.0,Sita,Furniture,Office Chair,Lalitpur,1.0,18000.0,Completed,18000.0,3600.0,900.0,17100.0,Regular Buyer
2,1003.0,Rohan,Electronics,Headphones,Bhaktapur,3.0,4500.0,Pending,13500.0,2700.0,675.0,12825.0,Bulk Buyer
3,1004.0,Anisha,Clothing,Jacket,Kathmandu,2.0,6500.0,Completed,13000.0,2600.0,650.0,12350.0,Regular Buyer
4,1005.0,Bibek,Electronics,Mobile Phone,Pokhara,1.0,55000.0,Cancelled,55000.0,11000.0,5500.0,49500.0,Regular Buyer
5,1006.0,Pragya,Books,Python Book,NaN,4.0,2200.0,Completed,8800.0,1760.0,440.0,8360.0,Bulk Buyer
6,1007.0,Nabin,Furniture,Desk,Lalitpur,2.0,25000.0,Completed,50000.0,10000.0,5000.0,45000.0,Regular Buyer
7,1008.0,Samir,Clothing,Sneakers,Pokhara,3.0,7500.0,Pending,22500.0,4500.0,1125.0,21375.0,Bulk Buyer
9,1010.0,Kiran,Books,Data Science Book,Bhaktapur,2.0,3500.0,Completed,7000.0,1400.0,350.0,6650.0,Regular Buyer
10,1011.0,Mina,Clothing,T-Shirt,Kathmandu,5.0,1800.0,Completed,9000.0,1800.0,450.0,8550.0,Bulk Buyer